'LOCKBOX_ADMIN_FAQ_LINK': "https://docs.google.com/document/d/1GEq8hbnjmH_4xq1WFgvuVrLMSTU1knjHLrKZyVqKzcY"
'LOCKBOX_EMAIL': "lockbox_kittens@example.com"
'LOCKBOX_PARTNER_FAQ_LINK': "https://docs.google.com/document/d/1GEq8hbnjmH_4xq1WFgvuVrLMSTU1knjHLrKZyVqKzcY"
