'LOCKBOX_ADMIN_FAQ_LINK': "http://www.example.com/admin_faq"
'LOCKBOX_EMAIL': "kittens@lockbox-example.com"
'LOCKBOX_PARTNER_FAQ_LINK': "http://www.example.com/partner_faq"
'REPLY_TO_EMAIL': "no-reply@lockbox-example.com"
