name: SecurityScans
on:
  pull_request:
    branches:
      - trunk

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bundler-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Bundler Audit
        run: gem install bundler-audit && bundler-audit check --update

